name: "issue link"
description: "A GitHub Action to add a related issue link to a pull request."
author: "tktcorporation"
inputs:
  branch-prefix:
    description: "The prefix of branch name."
    required: true
  repo-token:
    description: "Token for the repository. it can pass with {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "link"
  color: "gray-dark"
