name: 'Issue Link Comment'
on:
  pull_request:
    types: [opened]

jobs:
  issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add issue links with link-style option
        uses: ./
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: 'issue-'
          position: 'top' # nothing affects
          resolve: 'true'
          repository: 'tktcorporation/tktcorporation'
          link-style: 'comment'
